apiVersion: apps/v1
kind: Deployment
metadata:
  name: fail-once-demo
spec:
  replicas: 8
  selector:
    matchLabels:
      app: fail-once-demo
  template:
    metadata:
      labels:
        app: fail-once-demo
    spec:
      containers:
        - name: app
          image: busybox:1.36
          volumeMounts:
            - name: state
              mountPath: /state
          command:
            - /bin/sh
            - -c
            - |
              # Random startup delay 5–20 seconds
              START_DELAY=$(( ( $(od -An -N2 -tu2 /dev/urandom) ) % 16 + 5 ))
              echo "Startup delay: ${START_DELAY}s"
              sleep ${START_DELAY}
  
              # Decide randomly whether to fail (30% chance)
              FAIL_CHANCE=$(( ( $(od -An -N2 -tu2 /dev/urandom) ) % 100 ))
              if [ $FAIL_CHANCE -lt 30 ]; then
              echo "Random failure triggered (chance=${FAIL_CHANCE}%)"
              exit 1
              fi
  
              echo "Pod started successfully"
              sleep 3600
      volumes:
        - name: state
          emptyDir: {}